import { CountryInfo, Language } from './types';

export const COUNTRIES: CountryInfo[] = [
  {
    code: 'CO',
    nameEs: 'Colombia',
    nameEn: 'Colombia',
    treatyStatus: 'exam_required',
    canjeEs: 'Convenio de canje vigente. Los permisos profesionales (C, C+E, D) requieren superación de prueba teórica y práctica simplificada.',
    canjeEn: 'Reciprocity agreement in force. Professional permits (C, C+E, D) require passing a simplified theoretical & practical test.',
    averageTimeline: '10 - 12 semanas / weeks',
    successRate: '98%'
  },
  {
    code: 'MA',
    nameEs: 'Marruecos',
    nameEn: 'Morocco',
    treatyStatus: 'exam_required',
    canjeEs: 'Modificación del convenio en vigor (2024). Conductores de vehículos pesados (C/C+E) deben realizar examen teórico y práctico.',
    canjeEn: 'Modifying treaty active (2024). Heavy vehicle operators (C/C+E) must complete a theoretical and practical driving test.',
    averageTimeline: '12 - 14 semanas / weeks',
    successRate: '96%'
  },
  {
    code: 'PE',
    nameEs: 'Perú',
    nameEn: 'Peru',
    treatyStatus: 'exam_required',
    canjeEs: 'Convenio de canje activo. Licencias profesionales homologables mediante examen práctico en pista.',
    canjeEn: 'Active reciprocity agreement. Professional licenses exchangeable upon passing a closed-circuit maneuver test.',
    averageTimeline: '10 - 12 semanas / weeks',
    successRate: '97%'
  },
  {
    code: 'AR',
    nameEs: 'Argentina',
    nameEn: 'Argentina',
    treatyStatus: 'exam_required',
    canjeEs: 'Convenio aplicable. Canje de licencias pesadas coordinado con la DGT mediante validación y aptitud práctica.',
    canjeEn: 'Applicable treaty. Heavy permit exchange coordinated with DGT via validation and practical driving inspection.',
    averageTimeline: '8 - 10 semanas / weeks',
    successRate: '99%'
  },
  {
    code: 'EC',
    nameEs: 'Ecuador',
    nameEn: 'Ecuador',
    treatyStatus: 'exam_required',
    canjeEs: 'Convenio vigente. Requiere cita ante la DGT, verificación automática del ANT y prueba práctica.',
    canjeEn: 'Treaty in force. Requires DGT appointment, ANT verification, and practical test on maneuvers.',
    averageTimeline: '12 semanas / weeks',
    successRate: '95%'
  },
  {
    code: 'RO',
    nameEs: 'Rumanía (UE)',
    nameEn: 'Romania (EU)',
    treatyStatus: 'direct',
    canjeEs: 'Canje directo de la Unión Europea. Solo requiere verificación de idoneidad, tasa DGT y obtención directa sin exámenes.',
    canjeEn: 'Direct EU exchange. Requires verification of fitness, administrative fee, and direct issuance without testing.',
    averageTimeline: '2 - 4 semanas / weeks',
    successRate: '100%'
  },
  {
    code: 'UA',
    nameEs: 'Ucrania',
    nameEn: 'Ukraine',
    treatyStatus: 'direct',
    canjeEs: 'Régimen de canje extraordinario y simplificado por directrices europeas para conductores profesionales refugiados.',
    canjeEn: 'Extraordinary & simplified exchange regime regulated by EU directives for certified refugee professional drivers.',
    averageTimeline: '6 - 8 semanas / weeks',
    successRate: '98%'
  },
  {
    code: 'SV',
    nameEs: 'El Salvador',
    nameEn: 'El Salvador',
    treatyStatus: 'no_treaty',
    canjeEs: 'Sin convenio de canje directo automático. Requiere contratación en origen cupo ordinario con homologación o arraigo para la formación.',
    canjeEn: 'No automatic exchange. Requires origin labor quota recruitment, or professional certificate training paths.',
    averageTimeline: '18 - 24 semanas / weeks',
    successRate: '92%'
  },
  {
    code: 'OTHER',
    nameEs: 'Otros Países (Terceros Estados)',
    nameEn: 'Other Countries (Third-party)',
    treatyStatus: 'no_treaty',
    canjeEs: 'Proceso formal de visado de residencia y trabajo por cuenta ajena con tramitación de puesto de difícil cobertura (Catálogo SEPE).',
    canjeEn: 'Formal residence & work visa on behalf of employer with SEPE difficult-to-cover designation (Origin Sourcing).',
    averageTimeline: '16 - 22 semanas / weeks',
    successRate: '91%'
  }
];

export const TRANSLATIONS = {
  es: {
    heroTitle: 'Soluciones Legales en Extranjería para Conductores Profesionales de Flotas',
    heroSubtitle: 'Asesoría de Movilidad de Conductores de Transportes | AR Asesores',
    heroDesc: 'Portal corporativo líder para la gestión ágil de expedientes, convalidación y canje de permisos DGT, cursos CAP y contratación en origen de conductores extranjeros de camión, tráiler y autobús.',
    btnDiagnostic: 'Evaluar Viabilidad',
    btnServices: 'Nuestros Servicios',
    stat1Title: 'Experiencia Sectorial',
    stat1Desc: 'Especialización jurídica ininterrumpida en extranjería y normativa de transportes.',
    stat2Title: 'Eficacia de Canje',
    stat2Desc: 'Garantía de resoluciones positivas en permisos de residencia y autorizaciones de conducción.',
    stat3Title: 'Conductores Incorporados',
    stat3Desc: 'Choferes extranjeros plenamente operativos y convalidación completada con éxito.',
    sectionServices: 'Nuestros Servicios de Extranjería',
    servicesTitle: 'Gestión Integral en Extranjería y Transportes de Conductores',
    servicesSubtitle: 'Tramitamos todas las fases de la regularización: selección y contratación en origen, visados consulares, convalidación de permisos DGT, habilitación del CAP y tarjeta de tacógrafo.',
    
    modIntTitle: 'MÓDULO INTERNACIONAL',
    modIntSubtitle: 'Selección en Origen y Checking de Documentación',
    modIntDesc: 'Identificamos conductores profesionales cualificados y gestionamos la compilación de toda la documentación necesaria para realizar las solicitudes ante las Oficinas de Extranjería y Consulados.',
    modIntBullet1: 'Auditoría de perfiles profesionales',
    modIntBullet2: 'Gestión de autorizaciones de residencia y trabajo',
    
    modNacTitle: 'MÓDULO NACIONAL',
    modNacSubtitle: 'Integración Logística en España',
    modNacDesc: 'Tramitamos el canje del permiso de conducir, la obtención del CAP y de la tarjeta de Tacógrafo Digital, asegurando que el conductor sea plenamente operativo en el territorio nacional lo antes posible.',
    modNacBullet1: 'Canje de licencias de conducir extranjeras',
    modNacBullet2: 'Obtención del tacógrafo digital y el CAP',

    sectionMethod: 'Metodología AR',
    methodTitle: 'Un proceso estructurado para la obtención de permisos de trabajo',
    methodSubtitle: 'Cuatro pasos estratégicos para fortalecer el capital humano de su flota con total seguridad jurídica y administrativa en el menor tiempo posible.',
    method1Title: '01. ANÁLISIS DE LA FLOTA',
    method1Desc: 'Evaluación de vacantes y perfiles técnicos y profesionales de la empresa nacional.',
    method2Title: '02. SELECCIÓN DE CONDUCTORES',
    method2Desc: 'Validación de capacitación, aptitudes y experiencia en el país de origen. Revisión por el equipo de RRHH de la empresa.',
    method3Title: '03. TRAMITACIÓN DE EXPEDIENTES',
    method3Desc: 'Gestión de la documentación, presentación y seguimiento riguroso de los expedientes presentados ante las Oficinas de Extranjería.',
    method4Title: '04. HOMOLOGACIÓN Y OPERATIVIDAD',
    method4Desc: 'Canje de permisos de conducción, obtención de los certificados exigidos por la normativa española (CAP y Tacógrafo) e incorporación efectiva.',

    sectionCalculator: 'ASISTENTE DE COMPLIANCE',
    calculatorTitle: 'Calculadora de Viabilidad Legal para Conductores Extranjeros',
    calculatorSubtitle: 'Evalúe al instante la idoneidad y el canal administrativo idóneo para incorporar conductores internacionales a su flota española de manera legal.',
    selectCountry: 'País de Origen del Conductor',
    selectLicense: 'Permiso Especial a Tramitar / Homologar',
    licenseC: 'Clase C (Camiones rígidos > 3.500 kg)',
    licenseCE: 'Clase C+E (Tráileres y vehículos articulados)',
    licenseD: 'Clase D (Autobuses)',
    licenseDE: 'Clase D+E (Autobuses articulados)',
    licenseOther: 'Otros vehículos comerciales / Reparto',
    
    questionExp: '¿Cuenta el conductor con al menos 2 años de experiencia profesional demostrable con camiones o autobuses pesados?',
    questionRecord: '¿Dispone de certificado de antecedentes penales legalizado y apostillado sin anotaciones vigentes?',
    questionVisa: '¿Se encuentra actualmente libre de prohibiciones de entrada a la UE y con pasaporte en vigor (>12 meses)?',
    
    btnCalcular: 'Realizar Auditoría de Viabilidad',
    reportTitle: 'Informe Técnico de Viabilidad Legal',
    reportTimeline: 'Plazo Estimado de Incorporación:',
    reportRoute: 'Vía Jurídica Sugerida:',
    reportMatch: 'Requisitos Cumplidos:',
    reportPending: 'Acciones Necesarias:',
    highViability: 'Viabilidad Alta',
    mediumViability: 'Viabilidad Media con Pruebas',
    lowViability: 'Viabilidad Compleja / Vía Extraordinaria',
    
    formTitle: 'Hablemos del crecimiento de su empresa.',
    formSubtitle: 'Póngase en contacto con nuestros expertos para una consultoría inicial sin compromiso.',
    placeholderName: 'Su nombre completo',
    placeholderCompany: 'Nombre de la empresa',
    placeholderEmail: 'email@empresa.com',
    placeholderMsg: '¿En qué podemos ayudarle?',
    lblSubmit: 'Enviar Solicitud',
    alertSuccess: '¡Solicitud registrada correctamente! Su diagnóstico legal ha sido recopilado y nuestro equipo ejecutivo le contactará de inmediato.',
    
    murciaOffice: 'Murcia (Sede Central)',
    almeriaOffice: 'Almería',
    directContact: 'Atención Directa',
    consultationTitle: '1ª CONSULTA GRATIS',
    footerRights: 'Todos los derechos reservados. Consultoría legal de inmigración altamente especializada para el sector logístico, transporte de mercancías por carretera y transporte de pasajeros.',
    avisoLegal: 'Aviso Legal',
    politicaPrivacidad: 'Política de Privacidad',
    terminosServicio: 'Términos de Servicio',
    cookies: 'Cookies',

    activeRequests: 'Expedientes & Consultas Registradas',
    noActiveRequests: 'Aún no ha registrado consultas. Rellene el formulario o use el asistente de viabilidad para registrar su primer expediente.',
    viewActiveLogs: 'Control Fleet Manager',
    badgePending: 'En revisión',
    badgeApproved: 'Aprobado - Enlace DGT',
    exportLabel: 'Exportar Ficha de Candidato'
  },
  en: {
    heroTitle: 'Corporate Immigration & Legal Mobility for Professional Fleet Drivers',
    heroSubtitle: 'Heavy Transport International Sourcing & DGT Licensing | AR Asesores',
    heroDesc: 'Leading corporate portal for fast-track immigration files, Spanish DGT driving permit exchanges (canje), CAP professional certification, and origin recruiting of skilled heavy-truck and bus drivers.',
    btnDiagnostic: 'Verify Feasibility',
    btnServices: 'Immigration Services',
    stat1Title: 'Logistics Legal Expertise',
    stat1Desc: 'Decades of direct work in heavy transport immigration and regulatory adherence.',
    stat2Title: 'DGT Exchange Rate',
    stat2Desc: 'Proven success rate in processing foreign driver license exchanges and work visas.',
    stat3Title: 'Active Fleet Drivers',
    stat3Desc: 'Fully operational professional drivers integrated safely into Spanish fleets.',
    sectionServices: 'Our Immigration Services',
    servicesTitle: 'End-to-End International Driver Compliance',
    servicesSubtitle: 'We handle every stage of onboarding: from recruitment in third-party countries to work visas, DGT driver license convalidation, CAP courses, and tachograph cards.',
    
    modIntTitle: 'INTERNATIONAL MODULE',
    modIntSubtitle: 'Origin Recruitment & Document Verification',
    modIntDesc: 'We identify fully qualified professional drivers and manage the compilation of all legal documentation required for submission before immigration offices and embassies.',
    modIntBullet1: 'Professional profile and resume auditing',
    modIntBullet2: 'Residence & work permit request management',
    
    modNacTitle: 'NATIONAL MODULE',
    modNacSubtitle: 'Logistics Deployment in Spain',
    modNacDesc: 'We expedite the official foreign driving license exchange (canje), the professional certificate (CAP), and the Digital Tachograph card, ensuring they drive with optimal compliance.',
    modNacBullet1: 'Official foreign driving license exchanges',
    modNacBullet2: 'CAP and digital tachograph card acquisition',

    sectionMethod: 'AR Methodology',
    methodTitle: 'A Structured Process for Securing Work Permits',
    methodSubtitle: 'Four strategic stages to fortify your fleet capital with absolute legal and administrative support in the shortest timeframe.',
    method1Title: '01. FLEET REQUIREMENTS AUDIT',
    method1Desc: 'Evaluation of local vacancies, technical fleet needs and target professional driver profiles.',
    method2Title: '02. DRIVER SOURCING & VETTING',
    method2Desc: 'Validation of professional permits, skills, and backgrounds at the origin country. Human Resources coordination.',
    method3Title: '03. LEGAL FILE ADVOCACY',
    method3Desc: 'File preparation, swift submission, and strict tracking before the Foreign Offices and consular delegations.',
    method4Title: '04. EXCHANGES & OPERATIONAL DEPLOYMENT',
    method4Desc: 'Fast-tracking license exchange (Canje), required Spanish test passes (CAP/Tachograph) and instant fleet onboarding.',

    sectionCalculator: 'COMPLIANCE COMPANION',
    calculatorTitle: 'Foreign Driver Regulatory Audit Assistant',
    calculatorSubtitle: 'Assess immediately the legal feasibility and optimal visa/reciprocity path to hire international truck or bus drivers.',
    selectCountry: 'Driver\'s Country of Origin',
    selectLicense: 'Desired Spanish License Grade',
    licenseC: 'Class C (Rigid Trucks > 3,500 kg)',
    licenseCE: 'Class C+E (Articulated Rigids / Trailers)',
    licenseD: 'Class D (Buses & Coaches)',
    licenseDE: 'Class D+E (Articulated Buses / Coaches)',
    licenseOther: 'Other Commercial Permits',
    
    questionExp: 'Does the candidate hold at least 2 years of certified heavy truck/bus driving history?',
    questionRecord: 'Are they in possession of an official, apostilled/legalized non-criminal record check?',
    questionVisa: 'Are they free of EU travel bans and holding a valid passport (>12 months remain)?',
    
    btnCalcular: 'Execute Compliance Feasibility Audit',
    reportTitle: 'Legal Feasibility Technical Audit',
    reportTimeline: 'Estimated Fleet Deployment Time:',
    reportRoute: 'Recommended Juridical Route:',
    reportMatch: 'Matched Legal Requirements:',
    reportPending: 'Mandatory Next Actions:',
    highViability: 'High Feasibility Path',
    mediumViability: 'Standard Feasibility (Testing Required)',
    lowViability: 'Complex / Exceptional Labor Quota Route',
    
    formTitle: 'Let\'s power the growth of your company.',
    formSubtitle: 'Get in touch with our elite legal team for a free, no-obligation corporate diagnostic.',
    placeholderName: 'Your full name',
    placeholderCompany: 'Company name',
    placeholderEmail: 'email@company.com',
    placeholderMsg: 'How can we help your fleet compliance needs?',
    lblSubmit: 'Submit Formal Consultation',
    alertSuccess: 'Inquiry registered successfully! Your driving diagnostic has been logged and our executive team will contact you.',
    
    murciaOffice: 'Murcia (Headquarters)',
    almeriaOffice: 'Almería Office',
    directContact: 'Direct Assistance',
    consultationTitle: 'FREE FIRST ANALYSIS',
    footerRights: 'All rights reserved. Highly specialized legal immigration consulting services for the logistics, heavy road transport, and bus passenger sectors.',
    avisoLegal: 'Legal Notice',
    politicaPrivacidad: 'Privacy Policy',
    terminosServicio: 'Terms of Service',
    cookies: 'Cookies Policy',

    activeRequests: 'Logged Expediencies & Consultations',
    noActiveRequests: 'No logged inquiries found. Fill the form or use the assistant above to capture your first fleet candidate file.',
    viewActiveLogs: 'Fleet Manager Portal',
    badgePending: 'In Review',
    badgeApproved: 'DGT Verification Pending',
    exportLabel: 'Export Candidate Roadmap Summary'
  }
};
